# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - func-petcatalog-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/PetCatalog.Functions'
  DOTNET_VERSION: '9.0.x'  # Updated to 9.0.x for consistency
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: petcatalog

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Restore Project Dependencies'
        run: dotnet restore

      - name: 'Build Project'
        run: dotnet build --configuration Release --no-restore

      - name: 'Publish Azure Functions with .NET 9 optimizations'
        shell: bash
        run: |
          dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/PetCatalog.Functions.csproj \
            --configuration Release \
            --output ./publish \
            --no-build \
            --runtime win-x64 \
            --self-contained false \
            /p:PublishReadyToRun=true
      
      - name: 'Run Unit Tests'
        run: dotnet test tests/PetCatalog.UnitTests --configuration Release --no-build
      
      - name: 'Run Integration Tests'
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=${{ env.POSTGRES_DB }};Username=${{ env.POSTGRES_USER }};Password=${{ env.POSTGRES_PASSWORD }}"
        run: dotnet test tests/PetCatalog.IntegrationTests --configuration Release --no-build
      
      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Configure Function App for .NET 9'
        run: |
          az functionapp config set \
            --resource-group rg-adoggami-prod \
            --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
            --net-framework-version v9.0 \
            --use-32bit-worker-process false

          az functionapp config appsettings set \
            --resource-group rg-adoggami-prod \
            --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
            --settings FUNCTIONS_WORKER_RUNTIME=dotnet-isolated \
                      FUNCTIONS_EXTENSION_VERSION=~4 \
                      WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED=1
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: './publish'